language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cd
  - git clone https://github.com/maxmind/libmaxminddb.git
  - cd libmaxminddb
  - ./bootstrap && ./configure && make && sudo make install
  - cd $HOME/maxmind
  - git clone https://github.com/maxmind/MaxMind-DB-perl.git
  - cpanm --notest Devel::Cover::Report::Coveralls
  - cd $HOME/maxmind/GeoIP2-perl
script:
  perl Makefile.PL build && cover -test
after_success:
  cover -report coveralls
notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
